### ISSUE TITLE
Invalid requirement in requirements.txt

### ISSUE THREAD

**Issue by haorongchen1015** [ghdtjr/A-LLMRec#2]
Hi,  

When trying to install the dependencies from `requirements.txt`, I encountered the following error:

ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

When I try to remove the line, the line below still have this problem. 

Thanks,

**Comment by ghdtjr** [comment]
Well, I have no idea about this issue.
Have you tried this below command?
I've created the requirements.txt file with conda.
If you are facing issues with the right command, it seems the versions of conda do not match.

"conda create --name [env] --file [this file]"

**Comment by haorongchen1015** [comment]
Thank you for your suggestion. I tried using the command you provided, and I'm pleased to inform you that it worked. The environment configuration was successful, and the issue with the conda versions has been resolved.

**Comment by haorongchen1015** [comment]
Hi,
There is another question. When I using that "conda create --name [env] --file requirements.txt"
It says
PackagesNotFoundError: The following packages are not available from current channels:
# （The number of packages not found is far greater than listed below）
  - sympy==1.12=pypi_0
  - jupyter_client==7.3.4=pyhd8ed1ab_0
  - triton==2.1.0=pypi_0
  - decorator==5.1.1=pyhd8ed1ab_0
  - matplotlib-inline==0.1.6=pyhd8ed1ab_0
  ...
Many thanks

**Comment by ghdtjr** [comment]
It appears that the uploaded requirements.txt file contains some packages that are installed on my Linux server.

I checked the other issue of [Anna-Saeed], I agree with [Ansa-Saeed](https://github.com/Ansa-Saeed)'s suggestion: "I am installing only specific libraries separately, like..."
