### ISSUE TITLE
Early stop

### ISSUE THREAD

**Issue by 97z** [ghdtjr/A-LLMRec#7]
I wonder if the code has early stopping ? I notice that there has 11 epochs and every epoch has 2000 step. I user one V100 to run state 1. It seems it will cost 29 hours to run state 1. Is it right ? Thank you for any reply !

**Comment by ghdtjr** [comment]
We did not implement the early stopping. If you are dealing with a huge dataset such as Movies, that might be correct. If your purpose is just to reproduce our code, I suggest you to run with the smaller dataset. Or you can add early stopping.

**Comment by 97z** [comment]
Thank you for your reply !
