### ISSUE TITLE
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::Half != float

### ISSUE THREAD

**Issue by 97z** [ghdtjr/A-LLMRec#8]
When I run stage 2. The error happened. Has anyone meet the same error?

**Comment by ghdtjr** [comment]
I often faced that issue due to the quantizing of the LLM model. From below code in the llm4rec.py, try removing the load_in_8bit=True option.

self.llm_model = OPTForCausalLM.from_pretrained("facebook/opt-6.7b", torch_dtype=torch.float16, load_in_8bit=True, device_map=self.device)

**Comment by 97z** [comment]
> I often faced that issue due to the quantizing of the LLM model. From below code in the llm4rec.py, try removing the load_in_8bit=True option.
> 
> self.llm_model = OPTForCausalLM.from_pretrained("facebook/opt-6.7b", torch_dtype=torch.float16, load_in_8bit=True, device_map=self.device)

Thank you! I have done
