### ISSUE TITLE
Issue with Input Length Error during Inference

### ISSUE THREAD

**Issue by haorongchen1015** [ghdtjr/A-LLMRec#9]
Hello,

I have been using the Amazon Magazine_Subscriptions dataset (a smaller dataset compared to Movies_and_TV) for inference with your A-LLMRec model. However, I encountered the following error during execution:

ValueError: Input length of input_ids is 0, but `max_length` is set to 0. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

It seems the input_ids length is 0, which results in the error during the generation step. Could you provide any guidance on how to resolve this issue or adjust the model configuration accordingly?

Thank you for your time and assistance.

Best regards,
Haorong

**Comment by haorongchen1015** [comment]
data set movies and tvs also has this issue

**Comment by betoobusy** [comment]
me too！

**Comment by joyjiuyi** [comment]
Maybe you can solve this problem refer to https://github.com/boheumd/MA-LMM/issues/16.
